# Dependencies
markdown:         redcarpet
highlighter: 	  true
# highlighter:      pygments
# highlighter: 	 rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Peter Simon
tagline:          'Tech and Stuff but no tomatos ;-)'
description:      'Tech and Stuff but no tomatos ;-)'
url:              http://www.no-tomato.com
baseurl:          /

author:
  name:           'Peter Simon'
  url:            https://twitter.com/no_tomato_

paginate:         5

